### PR TITLE
Alfred snippets

### PR DESCRIPTION
**Pull request by valrus**
As promised, here's a script to generate Alfred snippets from the emoji template plist. I tested it by verifying that the output (.alfredsnippets file) loads correctly into Alfred 3.

A couple other things:
* I included the output of the script in the root dir of the repo since I noticed there was also a .kmmacros file there.
* I cleaned up `update-km.py` a little because I'm a stickler for Python idioms. In particular I but the main block of code in a `main()` function and switched from using Python's XML parser to one specifically intended for .plist files. I verified that it produces output identical to what was there before my changes.

### CODE REVIEW

**Comment by valrus** [comment]
Oh, I didn't update the README. But you should probably do that yourself.

**Comment by warpling** [comment]
You are awesome!! And the Python fixes are extra appreciated. Before I merge, you don't suppose there's a good, straight-forward way we could combine the macro scripts?

**Comment by valrus** [comment]
Depends on what you mean by "straightforward" and "combine." 😛

I'm guessing you mean just regenerate both the .km output (and anything else in the templates) and the Alfred output at the same time? That would be simple enough.

**Comment by valrus** [comment]
OK, updated. The new script is just `update-output.py` and it does what `update-km.py` and `update-alfred.py` used to do.

**Comment by warpling** [comment]
Perfect—Thank you!! 😃

**Pull request merged**
