### PR TITLE
bash install/uninstall script

### PR DESCRIPTION
**Pull request by mshick**
I put together this script to install and uninstall the macmoji as text replacements. My goal was to create something that would allow this package to be placed on Homebrew, since I could imagine that being a very convenient way to install it.

This script provides two commands `macmoji install` and `macmoji uninstall`. Install will add the macmoji to your existing text replacements. Uninstall will safely remove only the text replacements that match the phrase and shortcut defined by the macmoji plist.

It's somewhat more complicated than one might initially expect because of the need to update the UserDictionary database, as well as the GlobalPreferences file.

The very simple homebrew install formula is [here](https://github.com/mshick/homebrew-personal/blob/master/Formula/macmoji.rb). If you like this whole idea I'd add a little text and link to whatever release you cut, then submit to Homebrew for inclusion.

Thanks! Cool utility!

### CODE REVIEW

**Comment by warpling** [comment]
I love this! This was my original intention before being totally baffled by sqlite and discovering the drag'n'drop plist trick ;)

Which OSes have you tested this on? I noticed `ZUSERDICTIONARYENTRY` seemed to change in structure sometimes, but I could be wrong!

**Comment by mshick** [comment]
Only on Sierra. It should work on El Capitan, and I believe Yosemite. I don't have those environments available to test on though.

**Comment by warpling** [comment]
Damn, me neither. I'll add a warning to the README for now.

**Comment by warpling** [comment]
When I ran install I got a few warnings:

```
./scripts/macmoji: line 5: realpath: command not found
Installing Macmoji text replacements...
Print: Entry, ":0:shortcut", Does Not Exist
Print: Entry, ":0:phrase", Does Not Exist
```

on uninstall:

```
./scripts/macmoji: line 5: realpath: command not found
Uninstalling Macmoji text replacements...
Print: Entry, ":0:shortcut", Does Not Exist
Print: Entry, ":0:phrase", Does Not Exist
Print: Entry, ":NSUserDictionaryReplacementItems:1105:replace", Does Not Exist
Print: Entry, ":NSUserDictionaryReplacementItems:1105:with", Does Not Exist
```

I almost stopped the script—thinking it failed—before noticing it was still running. Maybe we could make it a bit more reassuring with emoji? ;)
`Adding emojis!… Hold tight ✌️`
`Done! 😁`

**Comment by mshick** [comment]
I will add that in, see if I can debug by installing on a couple machines, and re-submit. Thanks!

**Comment by warpling** [comment]
Rad!

**Pull request merged**
