### PR TITLE
Keyboard Maestro Version

### PR DESCRIPTION
**Pull request by rael9**
I've added a Keyboard Maestro 6 macro version of the emoji substitution, which works in Chrome, and should work pretty much anywhere, as long as you have/use Keyboard Maestro.

### CODE REVIEW

**Comment by warpling** [comment]
This is rad @rael9! Mind adding the emoji in the latest commit before we merge? 

If you created this with a script it'd be fantastic to have that hosted somewhere (See @lumaxis's Alfred port in #16) so updates can be made easily in the future.

I'm also very open to ideas on how we can best organize these different substitution files!

**Comment by rael9** [comment]
Sure can! I didn't use a script, but I was literally just about to create one for that very reason. You read my mind 😄

**Comment by rael9** [comment]
@warpling The emoji are up-to-date, and I added a python script to keep things up to date. Just need to run 'python update-km.py' while in the scripts directory.

**Comment by rael9** [comment]
@warpling I have updated the script so that it can be used for other formats as well. If other formats are needed, they can be added to the settings.json file in the scripts folder with a name (which corresponds to the filename) and a data_format (which uses the {placeholder} and {emoji} placeholders to designate where those values go. Then a template can be added to the templates folder with a {0} where the data should go that has the same filename with .template at the end. Run the script, and all of the files are generated 😄 

Let me know what you think.

**Comment by warpling** [comment]
This is fantastic! Thank you so much @rael9!!

**Pull request merged**
