### PR TITLE
Name things as they should be

### PR DESCRIPTION
**Pull request by pschambacher**
@warpling 

explanation

:trollface:

### CODE REVIEW

**Comment by warpling** [comment]
😂

**Comment by warpling** [comment]
😏 In all seriousness I'd merge `:handegg:` as an addition! Also good call on `:rugby:`—much better than the default.

**Comment by pschambacher** [comment]
There 😉 
I also aliased `soccer` with `eu_football` because I'm nice like that 😄

**Comment by warpling** [comment]
I'm down with that ;) 
One last thing! Mind running the python script in /scripts so that the `.kmmacros` file gets update too ([instructions](python scripts/update-km.py))  Let me know if you have any issues running it!

**Comment by pschambacher** [comment]
:haircut_man: 👍 :shipit:

**Pull request merged**
